pipeline {
    agent any

    environment {
        IMAGE_NAME = "bhanusree03/jenkins-demo"
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code'
            }
        }

        stage('Build') {
            steps {
                dir('Task_9/jenkins-demo') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Task_9/jenkins-demo') {
                    sh 'mvn test'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                dir('Task_9/jenkins-demo') {
                    archiveArtifacts artifacts: 'target/*.jar'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Task_9/jenkins-demo') {
                    sh 'docker build -t $IMAGE_NAME:latest .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker push $IMAGE_NAME:latest'
            }
        }
    }
}
