pipeline {
    agent any

    stages {

        stage('Gitleaks Scan') {
            steps {
                dir('Task_16/gitleaks-jenkins-demo/gitleaks-demo') {
                    sh 'gitleaks dir .'
                }
            }
        }

        stage('Build') {
            steps {
                dir('Task_16/gitleaks-jenkins-demo/gitleaks-demo') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Task_16/gitleaks-jenkins-demo/gitleaks-demo') {
                    sh 'docker build -t bhanusree03/gitleaks-demo:latest .'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed due to detected secrets or build errors.'
        }
    }
}
